### ISSUE TITLE
Requirements problem.

### ISSUE THREAD

**Issue by SummerFall1819** [wzf2000/MACRec#6]
Hello there, when I trying to configure the requirements, I met some troubles.

The first thing is that your requirements lack the package `langchain_community`.

Secondly, after running `pip install -r requirements.txt` and doing the pre-processing, there is an error related to the version of the package. Here is the full trace.
```
Traceback (most recent call last):
  File "D:\MACRec\main.py", line 6, in <module>
    from macrec.tasks import *
  File "D:\MACRec\macrec\tasks\__init__.py", line 7, in <module>
    from macrec.tasks.pure_generation import PureGenerationTask as GenerationTask, TestGenerationTask
  File "D:\MACRec\macrec\tasks\pure_generation.py", line 9, in <module>
    from macrec.tasks.generation import GenerationTask
  File "D:\MACRec\macrec\tasks\generation.py", line 11, in <module>
    from macrec.systems import ReActSystem, ReflectionSystem, AnalyseSystem, CollaborationSystem
  File "D:\MACRec\macrec\systems\__init__.py", line 1, in <module>
    from macrec.systems.base import System
  File "D:\MACRec\macrec\systems\base.py", line 8, in <module>
    from macrec.agents import Agent
  File "D:\MACRec\macrec\agents\__init__.py", line 2, in <module>
    from macrec.agents.base import Agent, ToolAgent
  File "D:\MACRec\macrec\agents\base.py", line 7, in <module>
    from macrec.llms import BaseLLM, AnyOpenAILLM, OpenSourceLLM
  File "D:\MACRec\macrec\llms\__init__.py", line 4, in <module>
    from macrec.llms.opensource import OpenSourceLLM
  File "D:\MACRec\macrec\llms\opensource.py", line 2, in <module>
    from jsonformer import Jsonformer
  File "D:\conda\envs\macrec\lib\site-packages\jsonformer\__init__.py", line 1, in <module>
    from jsonformer.main import Jsonformer
  File "D:\conda\envs\macrec\lib\site-packages\jsonformer\main.py", line 3, in <module>
    from jsonformer.logits_processors import (
  File "D:\conda\envs\macrec\lib\site-packages\jsonformer\logits_processors.py", line 2, in <module>
    from transformers import PreTrainedTokenizer, LogitsWarper, StoppingCriteria
ImportError: cannot import name 'LogitsWarper' from 'transformers'
```
The reason for that is the `jsonformer` package trying to use `LogitsWarper` in `transformer`, though this class is deprecated in version higher than 4.42. If possible, will you please help with the versions related for that?

**Comment by wzf2000** [comment]
The code works fine with `transformers` version 4.36.2. You can consider reinstalling that specific version.
